Thesis/force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>Main class for the description of the animal</description>
    <label>Animal</label>
    <nameField>
        <label>Imię</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Thesis/force-app/main/default/objects/MedicalExamination__c/MedicalExamination__c.object-meta.xml
<CustomObject>
    <label>Medical examination</label>
    <nameField>
        <label>Medical examination name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical examinations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Thesis/force-app/main/default/objects/MedicalExamination__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Medical examinations</relationshipLabel>
    <relationshipName>Medical_examinations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Thesis/force-app/main/default/objects/MedicalExamination__c/fields/ExaminationDate__c.field-meta.xml
<CustomField>
    <fullName>ExaminationDate__c</fullName>
    <label>Examination date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Thesis/force-app/main/default/objects/MedicalExamination__c/fields/NextExaminationDate__c.field-meta.xml
<CustomField>
    <fullName>NextExaminationDate__c</fullName>
    <label>Next examination date</label>
    <type>Date</type>
</CustomField>

Thesis/force-app/main/default/classes/HealthController.cls
public with sharing class HealthController {
    
    @AuraEnabled(cacheable=true scope='global')
    public static MedicalExamination__c[] getAllExaminationDates(String animalId) {
        return [
            SELECT Id, Animal__r.Name,Animal__r.Id, Animal__c, Name, ExaminationDate__c, NextExaminationDate__c FROM MedicalExamination__c WHERE Animal__r.Id =:animalId AND (ExaminationDate__c >= TODAY OR NextExaminationDate__c >= TODAY)
        ];
    }
}