Thesis/force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>Main class for the description of the animal</description>
    <label>Animal</label>
    <nameField>
        <label>Imię</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Thesis/force-app/main/default/objects/Animal__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF( NOT( ISBLANK(  Birthdate__c  ) ) ,
  IF( DATE( 2000 , MONTH( Birthdate__c ) , DAY( Birthdate__c ) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ),
     YEAR (Today()) - YEAR ( Birthdate__c ),
     YEAR (Today()) - YEAR ( Birthdate__c ) -1 ),
  null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Thesis/force-app/main/default/objects/Animal__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Pink</fullName>
            </value>
            <value>
                <fullName>Gray</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Thesis/force-app/main/default/objects/Animal__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Thesis/force-app/main/default/objects/Animal__c/fields/KindAnimal__c.field-meta.xml
<CustomField>
    <fullName>KindAnimal__c</fullName>
    <description>Describes the type of animal</description>
    <label>Animal kind</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cat</fullName>
            </value>
            <value>
                <fullName>Dog</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Thesis/force-app/main/default/objects/Animal__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Płeć</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Thesis/force-app/main/default/objects/Animal__c/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

Thesis/force-app/main/default/objects/Animal__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Thesis/force-app/main/default/classes/AnimalController.cls
public with sharing class AnimalController {
    @AuraEnabled(cacheable=true scope='global')
    public static Animal__c[] getAllAnimals() {
        return [
            SELECT Id, Name, Age__c, Sex__c, Height__c, Weight__c, KindAnimal__c FROM Animal__c ORDER BY Name
        ];
    }

    @AuraEnabled(cacheable=true scope='global')
    public static Animal__c[] searchAnimals(String searchTerm, String color) {
        // Return all animals when no search term
        String query = '';
        searchTerm = searchTerm.trim();
        if (searchTerm == '' || color == 'Select') {
            return getAllAnimals();
        }

        if (color != 'Select'){
            query += ' AND Color__c = \'' + color + '\'';
        }

        // Prepare query paramters
        searchTerm = '%' + searchTerm + '%';

        String resultQuery = 'SELECT Id, Name, Age__c, Sex__c, Height__c, Weight__c, KindAnimal__c, Color__c FROM Animal__c WHERE Name LIKE \''+ searchTerm + '\'' + query +' ORDER BY Name';

        System.debug(resultQuery);

        // List<Animal__c> animals = (List<Animal__c>)Database.query(resultQuery);
        // Execute search query
        return (List<Animal__c>)Database.query(resultQuery);
        
    }


    // @AuraEnabled
    // public static Animal__c[] searchAnimalsWithFiltr(String color){
    //     return[
    //         SELECT Id,
    //             Name,
    //             Age__c,
    //             Sex__c,
    //             Height__c,
    //             Weight__c,
    //             KindAnimal__c,
    //             Color__c
    //         FROM Animal__c
    //         WHERE Color__c LIKE :color
    //         ORDER BY Name
    //     ];
    // }
}


// public with sharing class BearController {
//     @AuraEnabled(cacheable=true scope='global')
//     public static Bear__c[] getAllBears() {
//         return [
//             SELECT
//                 Id,
//                 Name,
//                 Age__c,
//                 Sex__c,
//                 Height__c,
//                 Weight__c,
//                 Location__Latitude__s,
//                 Location__Longitude__s,
//                 Supervisor__r.Name
//             FROM Bear__c
//             WITH SECURITY_ENFORCED
//             ORDER BY Name
//             LIMIT 50
//         ];
//     }

//     @AuraEnabled(cacheable=true scope='global')
//     public static Bear__c[] searchBears(String searchTerm) {
//         // Return all bears when no search term
//         searchTerm = searchTerm.trim();
//         if (searchTerm == '') {
//             return getAllBears();
//         }
//         // Prepare query paramters
//         searchTerm = '%' + searchTerm + '%';
//         // Execute search query
//         return [
//             SELECT
//                 Id,
//                 Name,
//                 Age__c,
//                 Sex__c,
//                 Height__c,
//                 Weight__c,
//                 Location__Latitude__s,
//                 Location__Longitude__s,
//                 Supervisor__r.Name
//             FROM Bear__c
//             WHERE Name LIKE :searchTerm
//             WITH SECURITY_ENFORCED
//             ORDER BY Name
//             LIMIT 50
//         ];
//     }
// }